Repository The-Bugger-Ducks/mood-hound-web, pull requests merged in 2023-09, with the labels that each got.

#10 Feat/dashboard
  package.json
  src/assets/themes/chakra.theme.ts
  src/assets/themes/mui.theme.ts
  src/components/.gitignore
  src/components/AlertModal/index.tsx
  src/components/AlertModal/props.ts
  src/components/ConfirmModal/index.tsx
  src/components/ConfirmModal/props.ts
  src/components/Header/index.tsx
  src/components/MenuWithIcon/index.tsx
  src/components/MenuWithIcon/props.ts
  src/components/Table/index.tsx
  src/components/Table/props.ts
  src/components/Table/styles.ts
  src/components/textInput/index.tsx
  src/components/textInput/props.ts
  src/pages/dashboard/ReviewAnalysis/constants.tsx
  src/pages/dashboard/ReviewAnalysis/index.tsx
  src/pages/dashboard/index.tsx
  src/routes.tsx
  src/utils/enums/routes.enum.ts
  yarn.lock
Labels: feature request

#14 feat: setup sonarqube
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  .github/workflows/sonarcloud.yml
  .gitignore
  sonar-project.properties
Labels: chore

#31 Refactor/update layout
  src/assets/images/logo.svg
  src/components/LatestReviews/index.tsx
  src/components/SystemUsers/UpdateRoleModal/index.tsx
  src/components/SystemUsers/index.tsx
  src/pages/UserRegistration/index.tsx
  src/pages/UserUpdate/index.tsx
  src/utils/handlers/userRole.handler.ts
Labels: p.o approval, review needed, refactor
